import Testing
import Foundation
@testable import MPXPrime

// Pins the sidebar enabled-state indicator semantics: which stages have
// an enable concept, which inherit from a parent, and which respond to
// the corresponding AppConfig flag flipping. The sidebar renders a small
// accent dot only when isStageEnabled returns true; nil and false both
// produce no dot.

@Suite("Stage enabled indicator")
@MainActor
struct StageEnabledIndicatorTests {

    private func makeViewModel() -> MPXPrimeViewModel {
        let tempPath = NSTemporaryDirectory()
            + "MPXPrime-StageEnabledTests-\(UUID().uuidString).ini"
        return MPXPrimeViewModel(configPath: tempPath)
    }

    @Test func stagesWithoutEnableConceptReturnNil() {
        let model = makeViewModel()
        let noBadgeStages: [Stage] = [
            .monitoring,
            .processingOverview,
            .processingFormatProfile,
            .processingCore,
            .processingFinalStage,
            .snapshots,
            .rdsProgram,
            .rdsRadiotext,
            .rdsLongPS,
            .rdsAF,
            .rdsSchedule,
            .rdsCarrier
        ]
        for stage in noBadgeStages {
            #expect(model.isStageEnabled(stage) == nil,
                "\(stage) should not advertise an enable state")
        }
    }

    @Test func dspStagesReflectTheirEnableFlags() {
        let model = makeViewModel()
        // Defaults: BassClipper on, DCClipper off, AGC on, PrimeBass off.
        #expect(model.isStageEnabled(.processingBassClipper) == true)
        #expect(model.isStageEnabled(.processingDCClipper) == false)
        #expect(model.isStageEnabled(.processingAGC) == true)
        #expect(model.isStageEnabled(.processingPrimeBass) == false)

        // Flip them — indicator follows.
        model.config.bassClipperEnabled = false
        model.config.primeBassEnabled = true
        model.config.widebandAGCEnabled = false
        #expect(model.isStageEnabled(.processingBassClipper) == false)
        #expect(model.isStageEnabled(.processingPrimeBass) == true)
        #expect(model.isStageEnabled(.processingAGC) == false)
    }

    @Test func rdsControlMirrorsMasterEnable() {
        let model = makeViewModel()
        #expect(model.isStageEnabled(.rdsControl) == true,
            "default config ships with RDS master on")
        model.config.enRDS = false
        #expect(model.isStageEnabled(.rdsControl) == false)
    }

    @Test func testToneRowReflectsSourceModeNotSourceSelection() {
        let model = makeViewModel()
        // Default sourceMode is "input" — Test Tone row shouldn't carry
        // an "active" badge unless audio is actually being generated by
        // the tone source.
        #expect(model.config.sourceMode == "input")
        #expect(model.isStageEnabled(.testTone) == false)
        model.config.sourceMode = "tone"
        #expect(model.isStageEnabled(.testTone) == true)
        model.config.sourceMode = "input"
        #expect(model.isStageEnabled(.testTone) == false)
    }

    @Test func compositeClipperAndBS412RespondToToggles() {
        let model = makeViewModel()
        #expect(model.isStageEnabled(.processingCompositeClipper) == true)
        #expect(model.isStageEnabled(.processingBS412) == false)
        model.config.compositeClipperEnabled = false
        model.config.bs412Enabled = true
        #expect(model.isStageEnabled(.processingCompositeClipper) == false)
        #expect(model.isStageEnabled(.processingBS412) == true)
    }
}
